# Generated by Django 4.2 on 2024-08-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('idioma', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=1)),
                ('creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Supervisores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombres', models.CharField(max_length=50)),
                ('idioma', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('estado', models.CharField(max_length=1)),
                ('creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombres', models.CharField(max_length=50)),
                ('idioma', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=1)),
                ('creacion', models.DateField()),
            ],
        ),
    ]
